### ISSUE TITLE
Transition to `main` default branch

### ISSUE THREAD

**Issue by just95** [FreeProving/free-proving-code#1]
## Description

We have decided to change the default branch of all repositories in the FreeProving organization from `master` to `main`. See FreeProving/guidelines#2 for more information.

## Tasks

The tasks below have to be completed for the transition to `main` as the new default branch. 

 - [x] Create a new branch `main` from the current `master`.
 - [x] Select `main` as the default branch in the repository settings on GitHub.
 - [ ] Add branch protection rules for `main` in the repository settings on GitHub.
 - [x] Change the CI pipeline (if any) to run on pushes to `main`.
 - [x] If there are open pull requests, set their target branch to `main`.
 - [x] Update links to the `master` branch such that they point to `main` instead.
 - [x] Finally, delete the `master` branch. If the repository's `master` branch has been referenced in a published paper, keep the `master` branch, delete all files and commit a README that links to the new default branch.

**Comment by ichistmeinname** [comment]
> Add branch protection rules for main in the repository settings on GitHub.

This option is not necessary here.
